version: '3.9'

services:
  app:
    container_name: simple-app
    build:
      context: .
      dockerfile: Dockerfile
    image: belvaaaaa/simple-app:latest
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
